# Generated by Django 4.2.4 on 2023-08-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='p_image',
        ),
    ]
