# Generated by Django 4.2.4 on 2023-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0002_rename_image_productimage_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
