# Generated by Django 4.2.4 on 2023-08-14 11:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0004_product_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_webp',
            field=django_resized.forms.ResizedImageField(crop=None, default=12, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='photos/product_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
