# Generated by Django 4.2.4 on 2023-08-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0005_productimage_image_webp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_webp',
        ),
    ]
