# Generated by Django 4.2.4 on 2023-08-14 15:32

from django.db import migrations
import mstore.fields
import mstore.models


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0006_remove_product_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_webp',
            field=mstore.fields.WEBPField(default=12, height_field='height', upload_to=mstore.models.image_folder, verbose_name='Image', width_field='width'),
            preserve_default=False,
        ),
    ]
