# Generated by Django 4.2.4 on 2023-08-20 10:18

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0008_rename_image_product_card_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_image', models.ImageField(upload_to='photos/product_images/%Y/%m/%d/')),
                ('scheme_image_webp', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='photos/product_images/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.product')),
            ],
        ),
    ]
