# Generated by Django 4.2.4 on 2024-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0011_remove_product_favourite_favouriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='mstore.customer'),
        ),
        migrations.DeleteModel(
            name='FavouriteProduct',
        ),
    ]
