# Generated by Django 4.2.4 on 2025-07-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0012_product_favourites_delete_favouriteproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
